/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110338-g4570ba5d86-20230421"
#endif /* AVUTIL_FFVERSION_H */
